feature/aos 5139 warning externalhost duplicated
Skatteetaten/boober pull request #404
Opened 2020-11-24 07:46 UTC by bjartek

2020-11-24 12:20 UTC, kris456 requested changes

2020-11-24 12:20 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/AuroraDeploymentContextService.kt
> +        val duplicatedHosts =
eksplisitt type her for val

2020-11-24 12:20 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/AuroraDeploymentContextService.kt
> +    private fun findDuplicatedExternalHosts(contexts: List<AuroraDeploymentContext>): Map<AuroraDeploymentContext, List<String>> {
Vi kan kanskje dele denne opp litt slik at det blir litt enklere å forstå hva som foregår her

2020-11-25 06:41 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/RouteFeature.kt
> +val wembleyExternalHostAnnotationName = "wembley.sits.no|externalHost"
Godt poeng, når det er sagt bruker vi ikke det noen andre plasser i kodebasen.

2020-11-25 08:18 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/AuroraDeploymentContextService.kt
> +        val ctxs: Map<AuroraDeploymentContext, List<String>> = findDuplicatedExternalHosts(contexts)
Hva med ctxtsWithDuplicatedExternalHosts

2020-11-25 08:19 UTC, kris456 approved these changes

2020-11-26 08:53 UTC, kris456 approved these changes

2020-11-26 12:27 UTC, merged