Feature/aos 4875 mattermost notifications simple
Skatteetaten/boober pull request #407
Opened 2020-12-01 16:14 UTC by kris456

2020-12-03 10:15 UTC, kris456 commented
@bjartek bør vi også ha en simpel variant av auroraConfig her?
Altså :
```
notification:
  mattermost:
    test123: true
```

2020-12-03 11:55 UTC, bjartek requested changes
Ser veldig bra ut

2020-12-03 11:55 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/NotificationService.kt
> +    private fun List<Pair<AuroraDeployResult, Notification>>.groupDeployResultsByNotification(): Map<Notification, List<AuroraDeployResult>> =
Lag en toMultiMap på List<Pair<A,B>> og snu rekkefølgen her

2020-12-03 11:55 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/NotificationService.kt
> +    private fun AuroraDeployResult.findApplicationDeploymentSpec() = this.deployCommand
Jeg tror du kan bruke  ```this.deployCommand.resources.findResrouceType<ApplicationDeployment>()```
her

2020-12-03 11:56 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/NotificationService.kt
> +    private fun AuroraDeployResult.findApplicationDeploymentSpec() = this.deployCommand
selvfølgelig kan jeg det. Silly me

2020-12-04 10:42 UTC, bjartek requested changes

2020-12-04 10:42 UTC, bjartek commented on src/main/resources/application.yaml
> +        no.skatteetaten.aurora.boober: DEBUG
denne må bort

2020-12-04 10:42 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/NotificationService.kt
> +                       |##### Some applications could not be deployed
Kan alt dette komme med rød border rundt? attachment eller hva det heter

2020-12-04 10:42 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/NotificationService.kt
> +            val message = if (deployResult.success) adSpec.message ?: "" else deployResult.reason ?: "Unknown error"
Her ville jeg hatt med deployId hvis det er en feil

2020-12-04 10:42 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/NotificationService.kt
> +            |$listOfSuccessDeploys
Kan dette komme med grønn border?

2020-12-09 09:52 UTC, bjartek approved these changes

2020-12-10 13:09 UTC, merged