Feature/aos 5175 herkimer to secret
Skatteetaten/boober pull request #422
Opened 2021-01-22 09:14 UTC by kris456

2021-01-25 13:21 UTC, kris456 commented on src/main/resources/application.yaml
> +        url: https://herkimer-aurora.${openshift.cluster}.paas.skead.no
Denne må fjernes

2021-01-25 13:22 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/HerkimerVaultFeature.kt
> +        context.herkimerVaultCredentials
Hva er dette for noe rester? Fjern dette

2021-01-25 13:29 UTC, bjartek requested changes

2021-01-25 13:29 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/HerkimerVaultFeature.kt
> +                    credentialsConfiguredAsSingle.size > 1 -> {
mangler man ikke her at man også må sjekke at man fakstisk har spurt om single?

2021-01-25 13:29 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/HerkimerVaultFeature.kt
> +                val (credentialsConfiguredAsMultiple, credentialsConfiguredAsSingle) = vaultCredentials.partition { it.multiple }
hva med å bruke 
```

                val hasMultipe= vaultCredentials.any { it.multiple }
                val hasSingle= vaultCredentials.any { !it.multiple }
              
                val hasUc=vaultCredentials.any{ it.uppercaseEnvVarsSuffix}
                val hasLc=vaultCredentials.any{ !it.uppercaseEnvVarsSuffix}
```

2021-01-25 13:32 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/HerkimerVaultFeature.kt
> +                    credentialsConfiguredAsSingle.size > 1 -> {
Nei det gjør ikke det, jeg leser det feil, og her trenger du faktisk partition koden

2021-01-26 08:13 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/HerkimerVaultFeature.kt
> +                val (credentialsConfiguredAsMultiple, credentialsConfiguredAsSingle) = vaultCredentials.partition { it.multiple }
endret her:
https://github.com/Skatteetaten/boober/pull/422/commits/790a99eefa825f88699138fe7855f1f4f001e234

2021-01-26 16:09 UTC, stromland requested changes

2021-01-26 16:09 UTC, stromland commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/HerkimerVaultFeature.kt
> +                    "$FEATURE_FIELD/$key/multiple",
Hva er årsaken til at man må ha multiple felt? Fremfor å utlede antall ressurser/secrets

2021-01-26 16:09 UTC, stromland commented on src/main/kotlin/no/skatteetaten/aurora/boober/model/AuroraDeploymentSpec.kt
> +    inline operator fun <reified T> get(name: String): T = fields[name]?.value() ?: throw RuntimeException("Opps null value for key=$name")
Hva betyr Opps?

2021-01-26 16:14 UTC, stromland commented
Siden jeg ikke er kjent med koden så blir det litt pirk på navngivning etter slik jeg forstår koden. Men du må si ifra hvis du er uenig i forslagene.
Ønsker også å diskutere multiple feltet. Ellers så ser det veldig bra ut, godt jobbet!

2021-01-26 16:18 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/model/AuroraDeploymentSpec.kt
> +    inline operator fun <reified T> get(name: String): T = fields[name]?.value() ?: throw RuntimeException("Opps null value for key=$name")
Denne er feil. Dette er rester etter debug. Godt observert. Tar å fjerner denne. Er en egen oppgave på å kaste en exception/logge her ved null.

2021-01-26 16:20 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/HerkimerVaultFeature.kt
> +                    "$FEATURE_FIELD/$key/multiple",
Ved multiple=true så får du array notasjon på miljøvariabler. I min mening er det bedre at man deklarerer om man forventer flere verdier eller ikke. Da kan det være lettere å forstå hvilke miljøvariabler som blir returnert. Vi kan godt diskutere dette videre hvis du er uenig

2021-01-26 16:22 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/HerkimerVaultFeature.kt
> +private const val HERKIMER_SECRETS_KEY = "secrets"
Usikker om jeg vil sette den til CONTEXT_KEY. Da sier du implisitt at det kun kan være 1 entry i context. Hva med CONTEXT_SECRETS_KEY?

2021-01-26 16:28 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/HerkimerVaultFeature.kt
> +            }.groupBy { (vaultCredential, secrets) -> vaultCredential.prefix }
Det blir ikke helt det samme. Jeg ønsker å gruppere slik at jeg kan få en Map med alle vaultCredentials og tilhørende secrets med samme prefix. Er litt voldsomme strukturer som brukes for å finne alle som deler samme prefix. Alternativet hvis vi ikke har disse nøsta strukturene er at vi må duplisere kode og arbeid ved å lete frem verdiene som er nødvendige. Vi kan godt diskutere dette videre :)

2021-01-26 16:29 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/HerkimerVaultFeature.kt
> +    private fun generateHerkimerSecret(response: ResourceHerkimer, adc: AuroraDeploymentSpec): Secret {
det kan vi godt for min del. Forandrer det

2021-01-27 11:40 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/HerkimerVaultFeature.kt
> +private const val HERKIMER_SECRETS_KEY = "secrets"
endret litt her. Du kan jo se på det hvis du vil

2021-01-27 13:04 UTC, stromland approved these changes

2021-01-28 07:46 UTC, merged