Feature/aos-5477
Skatteetaten/boober pull request #436
Opened 2021-03-30 11:01 UTC by pax2k

Search for environment in all affiliations.

2021-04-08 11:32 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/controller/v2/MultiAffiliationControllerV2.kt
> +        // val refName = "feature/AOS-5477_hente_miljo_paa_tvers"
dette må bort før merge

2021-04-08 11:32 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/controller/v2/MultiAffiliationControllerV2.kt
> +                            it.cluster == "utv" // && it.testEnvironment
bør legge denne kommentaren inn nå og den skal vel også forandres til autodeploy?

2021-04-08 11:33 UTC, pax2k commented on src/main/kotlin/no/skatteetaten/aurora/boober/controller/v2/MultiAffiliationControllerV2.kt
> +                            it.cluster == "utv" // && it.testEnvironment
Godt poeng. Jeg kan starte å endre på det nå.

2021-04-09 11:23 UTC, kris456 requested changes

2021-04-09 11:23 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/controller/v2/MultiAffiliationControllerV2.kt
> +        val allApplications: List<MultiAffiliationResponse> =
Etter min mening så er det litt for mye logikk i controlleren. Det er mye her som hører hjemme i en service eller facade. Med tanke på forandringen med search så kunne man kanskje sett for seg at man skal ha en ApplicationSearchService og der kunne man nok hatt mye av dette. Man måtte da hatt en dto som går fra service laget til controlleren også gjør controlleren det om til en response.

2021-04-09 11:23 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/controller/v2/MultiAffiliationControllerV2.kt
> +        val allApplications: List<MultiAffiliationResponse> =
Et annet alternativ er å legge det i auroraConfigFacade for nå fram til man får mer realtert til search. Men da er det viktig at "MultiAffiliationResponse" blir laget i controller og ikke i facade

2021-04-09 11:23 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/facade/AuroraConfigFacade.kt
> +    fun findAllApplicationDeploymentSpecs(
så og si duplikat av findAuroraDeploymentSpecForEnvironment

2021-04-09 11:23 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/boober/controller/v2/MultiAffiliationControllerV2Test.kt
> +class MultiAffiliationControllerV2Test : AbstractControllerTest() {
Her trengs det litt flere teste i forhold til feilhåndtering med warning messages og hvis auroraConfigFacade kaster noe osv

2021-04-09 11:44 UTC, kris456 requested changes

2021-04-09 11:44 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/controller/v2/SearchController.kt
> +    fun findAll(@RequestParam(name = "environment") environment: String): ErrorsResponse {
Skal også autoDeploy være en queryparam?

2021-04-09 11:44 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/boober/facade/AuroraConfigFacadeTest.kt
> +import org.junit.jupiter.api.BeforeEach
Du må ha inn siste aurora code style fra bitbucket. Den inneholder en endring som gjør forskjell på sortering av imports

2021-04-09 11:46 UTC, pax2k commented on src/main/kotlin/no/skatteetaten/aurora/boober/controller/v2/SearchController.kt
> +    fun findAll(@RequestParam(name = "environment") environment: String): ErrorsResponse {
Jeg tror vi konkluderte med at det søkes på alt og at autoDeploy bare blir en del av responsen.

2021-04-12 11:13 UTC, kris456 commented
jeg og @pax2k jobbet litt med testene på fredag og la den logikken som tidligere lå i controlleren i AuroraConfigFacade, men det  hadde litt uheldige sideeffekter i forhold til testing av feilscenarioer. AuroraConfigFacade har et lokalt git repo den oppererer mot og det vil da være en litt større jobb å legge til noe mer der. 

Alternativ 1
Vi flytter koden for søk ut i en egen Service som heter f.eks SearchApplicationsService da har vi mulighet til å mocke ut AuroraConfigFacade, men jeg er selv usikker på om det er greit å kalle en facade fra service.

Alternativ 2 
La det stå slik det er og akseptere teknisk gjeld med planer om at søk skal utvides på senere tidspunkt og at det da fikses opp i

Alternativ 3
Flytte koden tilbake til Controlleren for å kunne mocke ut AuroraConfigFacade(Ikke tilhenger av det ettersom at jeg mener at denne koden ikke hører hjemme i en controller. Eventuelt hvilke grunner er det for at det bør være i controlleren?)

Hva tenker du om dette @stromland ?
Jeg er mest tilhenger av Alternativ 1, men jeg kan være med på at pga sprint slutt og slik så kan vi gå for alternativ 2

2021-04-13 06:24 UTC, stromland commented
@kris456 og @pax2k tenker at vi går for alternativ 2 siden det er en ny funksjonalitet. Fint hvis du lager en oppgave på det med alternativ 1 så legger vi den til i neste sprint.

2021-04-13 10:50 UTC, kris456 approved these changes
Godkjenner med forbehold om at det er opprettet oppgave for videre testing i neste sprint :) 
Ser bra ut!

2021-04-14 10:22 UTC, merged