Feature/aot-1218 cname
Skatteetaten/boober pull request #437
Opened 2021-04-06 08:00 UTC by nostra

Støtte opprettelse av AuroraCname CRD via Aurora-config og Judge Gavel. Doc (i Gavel) for hvordan dette ser ut for Boober: https://git.aurora.skead.no/projects/APSI/repos/gavel/browse/doc/content/doc/boober.md

2021-04-07 12:00 UTC, jarlehansen requested changes

2021-04-07 12:00 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/RouteFeature.kt
> +        val ars = context.routes.map {
Hva med å gjøre noe sånt?

```
override fun generate(adc: AuroraDeploymentSpec, context: FeatureContext): Set<AuroraResource> {
        val cnames: MutableSet<AuroraResource> = HashSet()
        return context.routes.map {
            val resource = it.generateOpenShiftRoute(
                routeNamespace = adc.namespace,
                serviceName = adc.name,
                routeSuffix = it.suffix(routeSuffix)
            )
            it.generateOpenShiftCname(routeNamespace = adc.namespace, routeSuffix = it.suffix(routeSuffix))?.let { cname ->
                cnames.add(generateResource(cname))
            }
            generateResource(resource)
        }.toMutableSet().apply {
            addAll(cnames)
        }
    }
```

2021-04-07 12:00 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/boober/model/openshift/AuroraCname.kt
> +    override fun setMetadata(metadata: ObjectMeta?) {
hvorfor er disse `var` og hvorfor er det settere her?

2021-04-07 12:27 UTC, nostra commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/RouteFeature.kt
> +        val ars = context.routes.map {
Jo, det er mye lurere. Endrer.

2021-04-07 12:34 UTC, nostra commented on src/main/kotlin/no/skatteetaten/aurora/boober/model/openshift/AuroraCname.kt
> +    override fun setMetadata(metadata: ObjectMeta?) {
Jeg fulgte mønsteret jeg så i ApplicationDeployment og BigIp. Alle disse arver ned fra `io.fabric8.kubernetes.api.model.HasMetadata`, og jeg antar at det er noe som enten alle trenger, eller som alle skulle ha vært foruten.

2021-04-07 13:05 UTC, jarlehansen approved these changes

2021-04-08 06:30 UTC, stromland reviewed
Kun et forlag til endring av metodenavn, ellers ser det veldig fint ut.

2021-04-08 06:30 UTC, stromland commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/RouteFeature.kt
> +    fun generateOpenShiftCname(routeNamespace: String, routeSuffix: String): AuroraCname? {
Endre denne til `generateAuroraCname`?

2021-04-08 06:36 UTC, nostra commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/RouteFeature.kt
> +    fun generateOpenShiftCname(routeNamespace: String, routeSuffix: String): AuroraCname? {
Godt forslag. Endret.

2021-04-08 06:45 UTC, stromland approved these changes

2021-04-08 06:58 UTC, merged