AOT-706 Validation error if invalid dns entry
Skatteetaten/boober pull request #444
Opened 2021-05-31 08:42 UTC by nostra

Hovedendringen er validering av dns-innslag. Dette gjøres 2 steder: 
- Ved validering av aurora-config for å gi fail-fast meldinger der mulig. 
- Etter opprettelse av aurora-config-objekt, hvor  @env@-uttrykk har blitt ekspandert (og dette har kanskje medført noe som vil gi en valideringsfeil)

Testene er forholdsvis verbose, men jeg synes selv ikke det gjør noe, siden jeg mener det gjør det klart hva som testes.

2021-06-02 11:28 UTC, stromland approved these changes

2021-06-02 12:44 UTC, kris456 requested changes

2021-06-02 12:44 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/utils/jsonNodeUtils.kt
> +        .any { return IllegalArgumentException("Invalid DNS node entry: \"${this.textValue()}\", disliked $it") }
Samme her som i StringUtils

2021-06-02 12:44 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/utils/jsonNodeUtils.kt
> +    if (this == null) {
Kunne du her ha fjernet ? fra JsonNode.validDnsPreExpansion()
Da kunne du istedenfor gjort slik i validator:
```
 AuroraConfigFieldHandler(
                "routeDefaults/host",
                defaultValue = "@name@-@affiliation@-@env@"
                defaultValue = "@name@-@affiliation@-@env@",
                validator = { it?.validDnsPreExpansion() }
            ),
```

Dvs at du da kan fjerne denne null checken. Bare en tanke

2021-06-02 12:44 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/RouteFeature.kt
> +            }.firstOrNull()
Man kan vel egentlig fjerne .firstOrNull. 
Man mister resten av exceptions her. Eller er det et ønske om at man kun får en feil?

2021-06-02 12:44 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/boober/feature/RouteFeatureTest.kt
> +        assertTrue(ex.message?.contains(("An error occurred")) ?: false, "Could not find text in ${ex.message}")
Det finnes hjelpemetoder slik at du slipper å sjekke exception på denne måten og du får ikke testet selve meldingen som vises. Ville heller gjort slik:
```kotlin
  assertThat {
            generateResources(
                """
                {
                  "route" : {
                    "foo" : {
                      "host": "X$twoHundred53",
                      "fullyQualifiedHost" : true
                    }
                  }
                }
                """.trimIndent(),
                createEmptyDeploymentConfig(),
                createdResources = 1
            )
        }.singleApplicationError("Invalid DNS node entry")
```

2021-06-02 12:44 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/boober/feature/RouteFeatureTest.kt
> +        assertThat { ex.message?.contains("DNS node") }
Samme her. Ville brukt singleApplicationError

2021-06-02 12:44 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/boober/feature/RouteFeatureTest.kt
> +        assertThat { ex.message?.contains("DNS node") }
Samme her ville brukt singleApplicationError

2021-06-02 12:44 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/boober/feature/RouteFeatureTest.kt
> +        assertThat { ex.message?.contains("DNS node") }
Samme her ville brukt singleApplicationError

2021-06-02 12:44 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/boober/feature/RouteFeatureTest.kt
> +        assertThat { ex.message?.contains("invalid dns name") }
Samme her ville brukt singleApplicationError

2021-06-02 12:44 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/boober/utils/StringUtils.kt
> +    this
hva tenker du @jarlehansen ?

2021-06-02 12:55 UTC, nostra commented on src/main/kotlin/no/skatteetaten/aurora/boober/utils/jsonNodeUtils.kt
> +    if (this == null) {
Ja, det er lurt. Kommer inn ved neste push.

2021-06-03 06:51 UTC, nostra commented on src/main/kotlin/no/skatteetaten/aurora/boober/utils/StringUtils.kt
> +    this
Skrevet om til noe som jeg tror er bedre.

2021-06-03 06:56 UTC, kris456 approved these changes
Ser bra ut dette :)

2021-06-03 10:10 UTC, welcor approved these changes
Liker godt testene - lette å overskue og samtidig ganske så komplette 👍

2021-06-07 05:39 UTC, merged