Feature/aos 5883 refaktorisere validering av konfig som bare kan spesifiseres i enkelte filer
Skatteetaten/boober pull request #459
Opened 2021-08-30 12:53 UTC by sirimykland

2021-08-30 13:26 UTC, sirimykland commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/Feature.kt
>  class HeaderHandlers private constructor(defaultAppName: String, defaultEnvName: String) {
Gjerne sjekk at allowedFilesTypes er riktig for feltene. Vi har lagt til allowedFilesTypes på mer enn bare envpointers

2021-09-01 13:55 UTC, bentsolheim requested changes
Hadde et par kommentarer, men dette ser i utgangspunktet veldig bra ut 😃

2021-09-01 13:55 UTC, bentsolheim commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/Feature.kt
> +                allowedFilesTypes = aboutFileTypes
Jeg lurer på om om env/name bør avgrenses kun til ENV?

2021-09-01 13:55 UTC, bentsolheim commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/Feature.kt
> +                allowedFilesTypes = aboutFileTypes
Jeg mener det er samme som for env/name

2021-09-01 13:55 UTC, bentsolheim commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/AuroraDeploymentSpecConfigFieldValidator.kt
> +                val fieldDeclaredInAllowedFile: Boolean =
Foreslår noe slikt:

`val fieldDeclaredInAllowedFile: Boolean = rawField.run { isDefault || e.isAllowedFileType(fileType) }`

Dere må da implementere

`fun isAllowedFileType(fileType: AuroraConfigFileType) = allowedFilesTypes?.contains(fileType) ?: true`

i AuroraConfigFieldHandler

2021-09-02 07:13 UTC, sirimykland commented on src/main/kotlin/no/skatteetaten/aurora/boober/feature/Feature.kt
> +                allowedFilesTypes = aboutFileTypes
enig

2021-09-02 10:44 UTC, bentsolheim approved these changes
Supert :)

2021-09-07 12:50 UTC, stromland approved these changes

2021-09-07 12:51 UTC, stromland commented
Må vente med å merge denne til PR #461 er ferdig.

2021-09-07 13:34 UTC, merged