initial commit
Skatteetaten/boober pull request #462
Opened 2021-09-08 14:21 UTC by sirimykland

2021-09-13 12:22 UTC, bentsolheim requested changes
Litt diverse kommentarer. Kan du ikke se hva du får ut av det, så kan vi evt. ta en skype?

2021-09-13 12:22 UTC, bentsolheim commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/exceptions.kt
> +    fun toValidationErrors(): List<ApplicationError> = listOf(
Ser ikke ut til at denne blir kalt opp noen gang?

2021-09-13 12:22 UTC, bentsolheim commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/exceptions.kt
> +    fun toValidationErrors(): List<ApplicationError> = listOf(
Ser ikke ut til at denne blir kalt opp noen gang?

2021-09-13 12:22 UTC, bentsolheim commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/exceptions.kt
> +                    it.first!!.cmd.applicationDeploymentRef.application,
Vil ikke dette føre til NPE dersom feilen er forårsaket av en exception i createAuroraDeploymentContext-kallet i createValidatedAuroraDeploymentContexts-metoden? Jeg ville jobbet mot at AuroraDeploymentContext aldri kan være null her istedenfor non-null assertion-operatoren.

2021-09-13 13:07 UTC, sirimykland commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/AuroraDeploymentContextService.kt
>      fun createValidatedAuroraDeploymentContexts(
createValidatedAuroraDeploymentContexts kalles tre ganger, hvor man i etterkant kaster MultiApplicationValidationException eller MultiApplicationValidationResultException, det er derfor ikke helt samme sjekk

2021-09-13 14:32 UTC, bentsolheim commented on src/main/kotlin/no/skatteetaten/aurora/boober/model/AuroraDeploymentContext.kt
> +    if (invalid.isNotEmpty()) {
Samme if som rett over?

2021-09-14 08:31 UTC, sirimykland commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/exceptions.kt
> +    fun toValidationErrors(): List<ApplicationError> = listOf(
Glemte å kalle den i ErrorHandler.kt, det er fikset nå

2021-09-14 08:32 UTC, sirimykland commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/exceptions.kt
> +    fun toValidationErrors(): List<ApplicationError> = listOf(
Glemte å kalle den i ErrorHandler.kt, det er fikset nå

2021-09-17 11:18 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/boober/model/errors.kt
> +    SKIPPED,
Hadde vært veldig fint med litt dokumentasjon på hva disse ulike error typene betyr

2021-09-17 11:19 UTC, jarlehansen approved these changes

2021-09-24 07:40 UTC, bentsolheim approved these changes

2021-09-24 08:10 UTC, merged