feature/AOS-5780-ownerReference-and-common-labels-not-included-in-SGOA
Skatteetaten/boober pull request #492
Opened 2021-12-10 09:04 UTC by martinrodland

2021-12-14 09:57 UTC, furode commented on src/test/kotlin/no/skatteetaten/aurora/boober/unit/S3StorageGridProvisionerTest.kt
> +        assertThat(response.credentials.size).isEqualTo(1)
En minor nitpick, med assertk.assertThat vil jeg anbefale å bruke `hasSize(int)` det gir litt klarere intensjon og feilmelding.

2021-12-14 10:10 UTC, furode approved these changes

2021-12-14 10:36 UTC, stromland requested changes
Ser bra ut, bare en ting på testen.

2021-12-14 13:42 UTC, martinrodland commented on src/test/kotlin/no/skatteetaten/aurora/boober/unit/S3StorageGridProvisionerTest.kt
> +        assertThat(response.credentials.size).isEqualTo(1)
fikset :)

2021-12-14 13:43 UTC, martinrodland commented on src/test/kotlin/no/skatteetaten/aurora/boober/feature/S3StorageGridFeatureTest.kt
> +                        this.labels = labels
Godt poeng! har nå fikset det nå :)

2021-12-16 07:51 UTC, stromland approved these changes

2022-01-03 10:50 UTC, martinrodland commented on src/main/kotlin/no/skatteetaten/aurora/boober/service/resourceprovisioning/S3StorageGridProvisioner.kt
> +    fun provisionMissingObjectAreas(applicationDeploymentId: String, requests: List<SgProvisioningRequest>): List<StorageGridObjectArea> {
Fjernet :)

2022-01-04 11:37 UTC, stromland approved these changes

2022-01-04 13:30 UTC, furode approved these changes

2022-01-05 08:45 UTC, merged