SITJ-2353 Valider at "fully qualified" faktisk ER fully qualified.
Skatteetaten/boober pull request #566
Opened 2022-08-17 11:33 UTC by welcor

2022-08-17 11:50 UTC, kris456 requested changes

2022-08-17 11:50 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/boober/feature/AuroraAzureAppSubPartTest.kt
> +    @ParameterizedTest
Jeg ville byttet til en litt mer spesifikk test. Vi har noen metoder som hjelper litt. Jeg fjernet @foo fordi at den treffer to stk validation feil. FQDN validation og gyldig dns validation feil. 

```suggestion
        @ParameterizedTest
    @CsvSource("invalid", "invalid.notam.skead.no", "multiple.dots.amutv.skead.no", "invalid.skead.no")
    fun `it is an error if azureAppFqdn is not a valid fqdn for azure`(fqdn: String) {
        assertThat {
            createAuroraConfigFieldHandlers(
                """{
             "azure" : {
                "azureAppFqdn": "$fqdn",
                "groups": ["APP_dev", "APP_DRIFT"]
              }
           }"""
            )
        }.singleApplicationError("must be a fully qualified domain name ")
    }

```

2022-08-18 13:03 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/boober/feature/AuroraAzureAppSubPartTest.kt
> +    @CsvSource("invalid", "@foo", "invalid.notam.skead.no", "multiple.dots.amutv.skead.no", "invalid.skead.no")
Den suggestionen funket ikke optimalt. Ble dobbelt opp her

2022-08-18 13:05 UTC, welcor commented on src/test/kotlin/no/skatteetaten/aurora/boober/feature/AuroraAzureAppSubPartTest.kt
> +    @CsvSource("invalid", "@foo", "invalid.notam.skead.no", "multiple.dots.amutv.skead.no", "invalid.skead.no")
Fikset :)

2022-08-18 13:06 UTC, kris456 approved these changes
LGTM!

2022-09-01 11:35 UTC, merged